language: python

python:
  - "2.7"

install:
  - pip install . --use-mirrors
  - pip install -r requirements/test.txt

script: 
  - cat example_projects.json
  - make test

after_success:
  - coveralls